#!/bin/sh
### BEGIN INIT INFO
# Provides:          k3s
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start k3s
### END INIT INFO

case "$1" in
  start)
    echo "Starting k3s..."
    /usr/local/bin/k3s server &
    ;;
  stop)
    echo "Stopping k3s..."
    killall k3s
    ;;
  *)
    echo "Usage: /etc/init.d/k3s-init {start|stop}"
    exit 1
    ;;
esac

